from typing import TypedDict, List, Optional, Annotated
import operator

# Reducer functions for LangGraph
def add_messages(left: list, right: list):
    return left + right

def add_lists(left: list, right: list):
    return left + right

class AgentState(TypedDict):
    """
    The state object passed between nodes in the Clause Analysis LangGraph.
    """
    # ==========================
    # 1. Core Input Context
    # ==========================
    chunk_id: str
    document_id: str
    original_text: str
    clause_type: str  # e.g., "Termination", "Financial"
    
    # Pre-fetched cross-references from the linking_service (Phase 2)
    direct_references: List[dict] 
    
    # The macro-level summary of the document (from overview_service)
    document_overview: str
    
    # ==========================
    # 2. Graph State & History
    # ==========================
    # Tracks conversations with the LLM (for Intent Router)
    messages: Annotated[list, add_messages]
    
    # Tracks how many times tools were called (to prevent infinite loops)
    tool_call_count: int
    
    # Tracks how many times the Verification node rejected the analysis
    verification_retry_count: int
    
    # Accumulated context from tools
    rag_results: Annotated[list, add_lists]
    web_results: Annotated[list, add_lists]
    
    # Any errors encountered during tool execution
    errors: Annotated[list, add_lists]
    
    # ==========================
    # 3. Outputs
    # ==========================
    # The feedback provided by the Verification node if the analysis was wrong
    verification_feedback: Optional[str]
    
    # The final structured JSON output generated by the Analysis node
    final_analysis: Optional[dict]
